-- Consultar Vuelo
SELECT 
    V.ID_VUELO,
    A.MODELO AS MODELO_AVION,
    (SELECT E.NOMBRE || ' ' || E.APELLIDO
        FROM EMPLEADOS E
        JOIN TRIPULACION T ON E.ID_EMPLEADO = T.EMPLEADOS_ID_EMPLEADO
        JOIN CARGO C ON E.CARGO_ID_CARGO = C.ID_CARGO
        WHERE T.VUELO_ID_VUELO = V.ID_VUELO AND C.NOMBRE = 'Piloto') AS PILOTO,
    SUM(CASE WHEN B.ESTADO = 'A' THEN 1 ELSE 0 END) AS ASIENTOS_OCUPADOS,
    SUM(CASE WHEN B.ESTADO = 'D' THEN 1 ELSE 0 END) AS ASIENTOS_DISPONIBLES,
    SUM(T.PRECIO) AS MONTO_GANADO
FROM VUELO V
JOIN AVION A ON V.AVION_ID_AVION = A.ID_AVION
LEFT JOIN BOLETO B ON V.ID_VUELO = B.VUELO_ID_VUELO
JOIN TARIFA T ON T.VUELO_ID_VUELO = V.ID_VUELO
WHERE V.ID_VUELO = 301 -- Reemplaza 301 con el CódigoVuelo deseado
GROUP BY V.ID_VUELO, A.MODELO;


-- Consultar Aviones 

SELECT 
    A.MODELO AS MODELO_AVION,
    A.MATRICULA,
    AR.NOMBRE AS AEROLINEA,
    A.ESTADO
FROM 
    AVION A
JOIN 
    AEROLINEA AR ON A.AEROLINEA_ID_AEROLINEA = AR.ID_AEROLINEA;



-- Consulta de empleados
SELECT 
    ID_EMPLEADO, 
    NOMBRE || ' ' || APELLIDO AS NOMBRE_COMPLETO, 
    NACIMIENTO, 
    CORREO, 
    DIRECCION
FROM 
    EMPLEADOS;

--Consulta de rutas
SELECT * FROM (
    SELECT 
        R.ID_RUTA, 
        A1.CODIGO_IATA AS ORIGEN, 
        A2.CODIGO_IATA AS DESTINO, 
        COUNT(V.ID_VUELO) AS CANTIDAD_VUELOS
    FROM 
        RUTAS R
    JOIN 
        AEROPUERTO A1 ON R.AEROPUERTO_ID_AEROPUERTO = A1.ID_AEROPUERTO
    JOIN 
        AEROPUERTO A2 ON R.AEROPUERTO_ID_AEROPUERTO2 = A2.ID_AEROPUERTO
    LEFT JOIN 
        VUELO V ON R.ID_RUTA = V.RUTAS_ID_RUTA
    GROUP BY 
        R.ID_RUTA, A1.CODIGO_IATA, A2.CODIGO_IATA
    ORDER BY 
        CANTIDAD_VUELOS DESC
) 
WHERE ROWNUM <= 5;
