--Consulta de empleados
SELECT 
    ID_EMPLEADO, 
    NOMBRE || ' ' || APELLIDO AS NOMBRE_COMPLETO, 
    NACIMIENTO, 
    CORREO, 
    DIRECCION
FROM 
    EMPLEADOS;

--Consulta de rutas
SELECT * FROM (
    SELECT 
        R.ID_RUTA, 
        A1.CODIGO_IATA AS ORIGEN, 
        A2.CODIGO_IATA AS DESTINO, 
        COUNT(V.ID_VUELO) AS CANTIDAD_VUELOS
    FROM 
        RUTAS R
    JOIN 
        AEROPUERTO A1 ON R.AEROPUERTO_ID_AEROPUERTO = A1.ID_AEROPUERTO
    JOIN 
        AEROPUERTO A2 ON R.AEROPUERTO_ID_AEROPUERTO2 = A2.ID_AEROPUERTO
    LEFT JOIN 
        VUELO V ON R.ID_RUTA = V.RUTAS_ID_RUTA
    GROUP BY 
        R.ID_RUTA, A1.CODIGO_IATA, A2.CODIGO_IATA
    ORDER BY 
        CANTIDAD_VUELOS DESC
) 
WHERE ROWNUM <= 5;
